name: expo_manager_booth_new
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Pakej sedia ada
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2

  # ✅ Pakej tambahan untuk memenuhi syarat rubrik (sekurang-kurangnya 3 pakej)
  intl: ^0.19.0        # Untuk format tarikh dan masa
  google_fonts: ^6.1.0 # Untuk font yang cantik (UI)

  # ✅ Firebase packages
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true